### ISSUE TITLE
sorry to bother, but how to use this code?

### ISSUE THREAD

**Issue by ChenYuhang243** [ysbecca/fwat#2]

**Comment by ysbecca** [comment]
Hi @githhhhh, sorry, unfortunately I've never documented this project, I just used it for a personal project. It is a Flask app, so if you would like to try using, you will have to set the root dir with your WSI files. And look around the code to see how to set up the db (_flask db init_, then _flask db migrate_). Sorry I cannot provide more support than that at this time.

**Comment by ChenYuhang243** [comment]
Oops, but thank you very much for your reply.
